2014-02-03T02:38:47.311505+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-03T02:38:47.311711+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
2014-02-03T02:38:47.311711+00:00 app[web.1]:     self._setup(name)
2014-02-03T02:38:47.311505+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-03T02:38:47.311711+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
2014-02-03T02:38:47.312137+00:00 app[web.1]:     'defaul': dj_database_url.config(
2014-02-03T02:38:47.312137+00:00 app[web.1]:   File "/app/eventex/settings.py", line 54, in <module>
2014-02-03T02:38:47.433249+00:00 app[web.1]: 2014-02-03 02:38:47 [2] [INFO] Reason: Worker failed to boot.
2014-02-03T02:38:47.432919+00:00 app[web.1]: 2014-02-03 02:38:47 [2] [INFO] Shutting down: Master
2014-02-03T02:38:48.652455+00:00 heroku[web.1]: State changed from starting to crashed
2014-02-03T02:38:48.637016+00:00 heroku[web.1]: Process exited with status 3
2014-02-03T02:40:09+00:00 heroku[slug-compiler]: Slug compilation started
2014-02-03T02:40:28.058567+00:00 heroku[api]: Deploy aededb4 by rg3915@yahoo.com.br
2014-02-03T02:40:28.142477+00:00 heroku[api]: Release v7 created by rg3915@yahoo.com.br
2014-02-03T02:40:28+00:00 heroku[slug-compiler]: Slug compilation finished
2014-02-03T02:40:28.813928+00:00 heroku[web.1]: State changed from crashed to starting
2014-02-03T02:40:32.970252+00:00 heroku[web.1]: Starting process with command `gunicorn eventex.wsgi`
2014-02-03T02:40:34.372658+00:00 app[web.1]: 2014-02-03 02:40:34 [2] [INFO] Listening at: http://0.0.0.0:7032 (2)
2014-02-03T02:40:34.372787+00:00 app[web.1]: 2014-02-03 02:40:34 [2] [INFO] Using worker: sync
2014-02-03T02:40:34.371952+00:00 app[web.1]: 2014-02-03 02:40:34 [2] [INFO] Starting gunicorn 18.0
2014-02-03T02:40:34.384216+00:00 app[web.1]: 2014-02-03 02:40:34 [7] [INFO] Booting worker with pid: 7
2014-02-03T02:40:34.530995+00:00 app[web.1]:     worker.init_process()
2014-02-03T02:40:34.530995+00:00 app[web.1]: Traceback (most recent call last):
2014-02-03T02:40:34.530995+00:00 app[web.1]: 2014-02-03 02:40:34 [7] [ERROR] Exception in worker process:
2014-02-03T02:40:34.530995+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-02-03T02:40:34.530995+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-02-03T02:40:34.530995+00:00 app[web.1]:     self.callable = self.load()
2014-02-03T02:40:34.531227+00:00 app[web.1]:   File "/app/eventex/wsgi.py", line 5, in <module>
2014-02-03T02:40:34.530995+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-02-03T02:40:34.530995+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-02-03T02:40:34.531227+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-02-03T02:40:34.530995+00:00 app[web.1]:     return self.load_wsgiapp()
2014-02-03T02:40:34.531227+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-02-03T02:40:34.531227+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-02-03T02:40:34.531227+00:00 app[web.1]:     __import__(module)
2014-02-03T02:40:34.531227+00:00 app[web.1]:     from django.core.wsgi import get_wsgi_application
2014-02-03T02:40:34.530995+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-02-03T02:40:34.531406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 12, in <module>
2014-02-03T02:40:34.531227+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 11, in <module>
2014-02-03T02:40:34.531227+00:00 app[web.1]:     from django.core.handlers import base
2014-02-03T02:40:34.531406+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-03T02:40:34.531227+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
2014-02-03T02:40:34.531406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-03T02:40:34.531884+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
2014-02-03T02:40:34.531227+00:00 app[web.1]:     from django.core.handlers.wsgi import WSGIHandler
2014-02-03T02:40:34.531406+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2014-02-03T02:40:34.531406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
2014-02-03T02:40:34.531406+00:00 app[web.1]:     signals.request_started.connect(reset_queries)
2014-02-03T02:40:34.531884+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
2014-02-03T02:40:34.531884+00:00 app[web.1]:   File "/app/eventex/settings.py", line 54, in <module>
2014-02-03T02:40:34.531884+00:00 app[web.1]:     'defaul': dj_database_url.config(
2014-02-03T02:40:34.531884+00:00 app[web.1]: NameError: name 'dj_database_url' is not defined
2014-02-03T02:40:34.531884+00:00 app[web.1]: Traceback (most recent call last):
2014-02-03T02:40:34.531884+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2014-02-03T02:40:34.531406+00:00 app[web.1]:     self._setup(name)
2014-02-03T02:40:34.531406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-03T02:40:34.531884+00:00 app[web.1]:     worker.init_process()
2014-02-03T02:40:34.531406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-03T02:40:34.531406+00:00 app[web.1]:     if settings.DEBUG:
2014-02-03T02:40:34.532061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-02-03T02:40:34.532061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-02-03T02:40:34.532061+00:00 app[web.1]:     self.callable = self.load()
2014-02-03T02:40:34.532061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-02-03T02:40:34.531884+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-02-03T02:40:34.532061+00:00 app[web.1]:     return self.load_wsgiapp()
2014-02-03T02:40:34.531884+00:00 app[web.1]:     __import__(name)
2014-02-03T02:40:34.532390+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
2014-02-03T02:40:34.532390+00:00 app[web.1]:     from django.core.handlers.wsgi import WSGIHandler
2014-02-03T02:40:34.532390+00:00 app[web.1]:     from django.core.wsgi import get_wsgi_application
2014-02-03T02:40:34.532061+00:00 app[web.1]:     __import__(module)
2014-02-03T02:40:34.532061+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-02-03T02:40:34.532390+00:00 app[web.1]:   File "/app/eventex/wsgi.py", line 5, in <module>
2014-02-03T02:40:34.532061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-02-03T02:40:34.532061+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-02-03T02:40:34.532390+00:00 app[web.1]:     from django.core.handlers import base
2014-02-03T02:40:34.532390+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 12, in <module>
2014-02-03T02:40:34.532390+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-03T02:40:34.532390+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-03T02:40:34.532390+00:00 app[web.1]:     signals.request_started.connect(reset_queries)
2014-02-03T02:40:34.532390+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 11, in <module>
2014-02-03T02:40:34.532061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-02-03T02:40:34.532563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
2014-02-03T02:40:34.532563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-03T02:40:34.532893+00:00 app[web.1]:     'defaul': dj_database_url.config(
2014-02-03T02:40:34.532563+00:00 app[web.1]:     if settings.DEBUG:
2014-02-03T02:40:34.532563+00:00 app[web.1]:     self._setup(name)
2014-02-03T02:40:34.532563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
2014-02-03T02:40:34.532563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-03T02:40:34.532563+00:00 app[web.1]:     __import__(name)
2014-02-03T02:40:34.532563+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2014-02-03T02:40:34.532563+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2014-02-03T02:40:34.532563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
2014-02-03T02:40:34.532893+00:00 app[web.1]: 2014-02-03 02:40:34 [7] [INFO] Worker exiting (pid: 7)
2014-02-03T02:40:34.653214+00:00 app[web.1]: 2014-02-03 02:40:34 [2] [INFO] Shutting down: Master
2014-02-03T02:40:34.532893+00:00 app[web.1]: NameError: name 'dj_database_url' is not defined
2014-02-03T02:40:34.653214+00:00 app[web.1]: 2014-02-03 02:40:34 [2] [INFO] Reason: Worker failed to boot.
2014-02-03T02:40:34.532893+00:00 app[web.1]:   File "/app/eventex/settings.py", line 54, in <module>
2014-02-03T02:40:36.175365+00:00 heroku[web.1]: Process exited with status 3
2014-02-03T02:40:36.189859+00:00 heroku[web.1]: State changed from starting to crashed
2014-02-03T02:40:36.761372+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=rg3915-wttd.herokuapp.com request_id=da5ff7d0-02a1-4fe4-bbd5-a08e3192dd85 fwd="177.141.225.233" dyno= connect= service= status=503 bytes=
2014-02-03T02:40:37.095378+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/favicon.ico host=rg3915-wttd.herokuapp.com request_id=8af7fbf8-8836-48ce-9a6e-8f9f07a932c0 fwd="177.141.225.233" dyno= connect= service= status=503 bytes=
