2014-02-03T03:10:35.028529+00:00 app[web.1]:     __import__(name)
2014-02-03T03:10:35.028529+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 3, in <module>
2014-02-03T03:10:35.028529+00:00 app[web.1]:     from django.contrib.auth.backends import RemoteUserBackend
2014-02-03T03:10:35.028529+00:00 app[web.1]:     from django.contrib.auth.models import Permission
2014-02-03T03:10:35.028529+00:00 app[web.1]:     class Permission(models.Model):
2014-02-03T03:10:35.028529+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/models.py", line 48, in <module>
2014-02-03T03:10:35.028704+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 96, in __new__
2014-02-03T03:10:35.028704+00:00 app[web.1]:     new_class.add_to_class('_meta', Options(meta, **kwargs))
2014-02-03T03:10:35.028704+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 264, in add_to_class
2014-02-03T03:10:35.028704+00:00 app[web.1]:     value.contribute_to_class(cls, name)
2014-02-03T03:10:35.028529+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 21, in import_by_path
2014-02-03T03:10:35.028704+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/options.py", line 124, in contribute_to_class
2014-02-03T03:10:35.028704+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 34, in __getattr__
2014-02-03T03:10:35.028704+00:00 app[web.1]:     return getattr(connections[DEFAULT_DB_ALIAS], item)
2014-02-03T03:10:35.028704+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 196, in __getitem__
2014-02-03T03:10:35.029177+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 170, in ensure_defaults
2014-02-03T03:10:35.029177+00:00 app[web.1]:     conn = self.databases[alias]
2014-02-03T03:10:35.028529+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 3, in <module>
2014-02-03T03:10:35.029177+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 161, in databases
2014-02-03T03:10:35.028704+00:00 app[web.1]:     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
2014-02-03T03:10:35.029177+00:00 app[web.1]:     raise ImproperlyConfigured("You must define a '%s' database" % DEFAULT_DB_ALIAS)
2014-02-03T03:10:35.029177+00:00 app[web.1]: ImproperlyConfigured: You must define a 'default' database
2014-02-03T03:10:35.029177+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/functional.py", line 49, in __get__
2014-02-03T03:10:35.028704+00:00 app[web.1]:     self.ensure_defaults(alias)
2014-02-03T03:10:35.029177+00:00 app[web.1]:     res = instance.__dict__[self.func.__name__] = self.func(instance)
2014-02-03T03:10:54.668821+00:00 app[web.1]:     return self.application(environ, start_response)
2014-02-03T03:10:54.668821+00:00 app[web.1]: Traceback (most recent call last):
2014-02-03T03:10:54.668821+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/dj_static.py", line 59, in __call__
2014-02-03T03:10:54.668821+00:00 app[web.1]: 2014-02-03 03:10:54 [7] [ERROR] Error handling request
2014-02-03T03:10:54.668821+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2014-02-03T03:10:54.668821+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2014-02-03T03:10:54.668821+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
2014-02-03T03:10:54.669068+00:00 app[web.1]:     module = import_module(module_path)
2014-02-03T03:10:54.669294+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 96, in __new__
2014-02-03T03:10:54.668821+00:00 app[web.1]:     self.load_middleware()
2014-02-03T03:10:54.669294+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 264, in add_to_class
2014-02-03T03:10:54.668821+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
2014-02-03T03:10:54.668821+00:00 app[web.1]:     mw_class = import_by_path(middleware_path)
2014-02-03T03:10:54.669068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 21, in import_by_path
2014-02-03T03:10:54.669068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
2014-02-03T03:10:54.669068+00:00 app[web.1]:     __import__(name)
2014-02-03T03:10:54.669068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 3, in <module>
2014-02-03T03:10:54.669294+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 34, in __getattr__
2014-02-03T03:10:54.669294+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 196, in __getitem__
2014-02-03T03:10:54.669294+00:00 app[web.1]:     value.contribute_to_class(cls, name)
2014-02-03T03:10:54.669956+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/functional.py", line 49, in __get__
2014-02-03T03:10:54.669068+00:00 app[web.1]:     from django.contrib.auth.backends import RemoteUserBackend
2014-02-03T03:10:54.669068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 3, in <module>
2014-02-03T03:10:54.669068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/models.py", line 48, in <module>
2014-02-03T03:10:54.669294+00:00 app[web.1]:     new_class.add_to_class('_meta', Options(meta, **kwargs))
2014-02-03T03:10:54.669068+00:00 app[web.1]:     from django.contrib.auth.models import Permission
2014-02-03T03:10:54.669068+00:00 app[web.1]:     class Permission(models.Model):
2014-02-03T03:10:54.669956+00:00 app[web.1]:     res = instance.__dict__[self.func.__name__] = self.func(instance)
2014-02-03T03:10:54.669956+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 170, in ensure_defaults
2014-02-03T03:10:54.669294+00:00 app[web.1]:     self.ensure_defaults(alias)
2014-02-03T03:10:54.669294+00:00 app[web.1]:     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
2014-02-03T03:10:54.669294+00:00 app[web.1]:     return getattr(connections[DEFAULT_DB_ALIAS], item)
2014-02-03T03:10:54.669956+00:00 app[web.1]:     conn = self.databases[alias]
2014-02-03T03:10:54.669707+00:00 heroku[router]: at=info method=GET path=/ host=rg3915-wttd.herokuapp.com request_id=44ffa787-2fee-451a-82c5-3a643a49e56e fwd="177.141.225.233" dyno=web.1 connect=1ms service=6ms status=500 bytes=135
2014-02-03T03:10:54.669956+00:00 app[web.1]:     raise ImproperlyConfigured("You must define a '%s' database" % DEFAULT_DB_ALIAS)
2014-02-03T03:10:54.669294+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/options.py", line 124, in contribute_to_class
2014-02-03T03:10:54.669956+00:00 app[web.1]: ImproperlyConfigured: You must define a 'default' database
2014-02-03T03:10:54.669956+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 161, in databases
2014-02-03T03:10:54.933543+00:00 heroku[router]: at=info method=GET path=/favicon.ico host=rg3915-wttd.herokuapp.com request_id=9626a027-c55e-4c76-99ab-0bc04a9b144e fwd="177.141.225.233" dyno=web.1 connect=5ms service=4ms status=500 bytes=135
2014-02-03T03:10:54.933964+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2014-02-03T03:10:54.933964+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/dj_static.py", line 59, in __call__
2014-02-03T03:10:54.933964+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
2014-02-03T03:10:54.933964+00:00 app[web.1]:     return self.application(environ, start_response)
2014-02-03T03:10:54.933964+00:00 app[web.1]: 2014-02-03 03:10:54 [7] [ERROR] Error handling request
2014-02-03T03:10:54.933964+00:00 app[web.1]: Traceback (most recent call last):
2014-02-03T03:10:54.933964+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2014-02-03T03:10:54.934222+00:00 app[web.1]:     __import__(name)
2014-02-03T03:10:54.934222+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 3, in <module>
2014-02-03T03:10:54.934222+00:00 app[web.1]:     from django.contrib.auth.backends import RemoteUserBackend
2014-02-03T03:10:54.934418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/options.py", line 124, in contribute_to_class
2014-02-03T03:10:54.933964+00:00 app[web.1]:     mw_class = import_by_path(middleware_path)
2014-02-03T03:10:54.934222+00:00 app[web.1]:     module = import_module(module_path)
2014-02-03T03:10:54.934222+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 21, in import_by_path
2014-02-03T03:10:54.934222+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
2014-02-03T03:10:54.933964+00:00 app[web.1]:     self.load_middleware()
2014-02-03T03:10:54.933964+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
2014-02-03T03:10:54.934418+00:00 app[web.1]:     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
2014-02-03T03:10:54.934418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 34, in __getattr__
2014-02-03T03:10:54.934994+00:00 app[web.1]:     conn = self.databases[alias]
2014-02-03T03:10:54.934418+00:00 app[web.1]:     value.contribute_to_class(cls, name)
2014-02-03T03:10:54.934222+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 3, in <module>
2014-02-03T03:10:54.934222+00:00 app[web.1]:     from django.contrib.auth.models import Permission
2014-02-03T03:10:54.934222+00:00 app[web.1]:     class Permission(models.Model):
2014-02-03T03:10:54.934418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 96, in __new__
2014-02-03T03:10:54.934222+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/models.py", line 48, in <module>
2014-02-03T03:10:54.934418+00:00 app[web.1]:     new_class.add_to_class('_meta', Options(meta, **kwargs))
2014-02-03T03:10:54.934994+00:00 app[web.1]: ImproperlyConfigured: You must define a 'default' database
2014-02-03T03:10:54.934994+00:00 app[web.1]:     raise ImproperlyConfigured("You must define a '%s' database" % DEFAULT_DB_ALIAS)
2014-02-03T03:10:54.934418+00:00 app[web.1]:     return getattr(connections[DEFAULT_DB_ALIAS], item)
2014-02-03T03:10:54.934418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 264, in add_to_class
2014-02-03T03:10:54.934418+00:00 app[web.1]:     self.ensure_defaults(alias)
2014-02-03T03:10:54.934994+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 170, in ensure_defaults
2014-02-03T03:10:54.934994+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/functional.py", line 49, in __get__
2014-02-03T03:10:54.934994+00:00 app[web.1]:     res = instance.__dict__[self.func.__name__] = self.func(instance)
2014-02-03T03:10:54.934418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 196, in __getitem__
2014-02-03T03:10:54.934994+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 161, in databases
